---
- name: Restart the Linux server and wait for Jenkins to be up
  hosts: all
  become: yes
  tasks:

    - name: Restart the server
      shell: |
        shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for server to be back online
      wait_for_connection:
        timeout: 600  # Wait for up to 10 minutes for the server to come back online

    - name: Wait for Jenkins service to be active
      wait_for:
        port: 8443  # Jenkins port
        delay: 10  # Initial delay before starting to check
        timeout: 2400  # 40 minutes in seconds
        state: started
        msg: "Jenkins service is not up after 40 minutes."

    - name: Ensure Jenkins service is running
      service:
        name: jenkins
        state: started
