AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an Auto Scaling Group and a Target Group

Parameters:
  VPCID:
    Type: String
    Description: VPC ID where resources will be created

  SubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the Auto Scaling Group

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair for SSH access to instances

  ImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for EC2 instances

Resources:
  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref SubnetIDs
      LaunchConfigurationName:
        Ref: MyLaunchConfig
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: MyAutoScalingInstance
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '1'
        PauseTime: PT5M
        WaitOnResourceSignals: true
    SuspendedProcesses:
      - Terminate
      - Launch
      - HealthCheck

  MyLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MyExistingSecurityGroup

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8443
      Protocol: HTTP
      VpcId: !Ref VPCID

Outputs:
  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group
    Value: !Ref MyAutoScalingGroup

  TargetGroupName:
    Description: Name of the Target Group
    Value: !Ref MyTargetGroup
